# Site settings
title: Manpi
description: 'Manpi - fashion perfect for you!'
url: 'http://manpi.uk'
baseurl: ''
google_analytics: 'UA-107290648-1'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Manpi'
  email: info@manpi.uk
  facebook_username: manpi.fashion
  linkedin_username: 11299156
  #linkedin_username:  manpi

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
